spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        default_batch_fetch_size: 100

springdoc:
  swagger-ui:
    path: /swagger-ui.html

server:
  forward-headers-strategy: framework
