--
-- PostgreSQL database dump
--

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.4 (Ubuntu 18.4-0ubuntu0.26.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: business_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.business_profile (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    business_name character varying(255) NOT NULL,
    business_registration_certificate_url character varying(255) NOT NULL,
    business_registration_number character varying(255) NOT NULL,
    business_type character varying(255) NOT NULL,
    member_id bigint NOT NULL,
    opened_date date NOT NULL,
    rejection_reason character varying(255),
    representative_name character varying(255) NOT NULL,
    reviewed_at timestamp(6) without time zone,
    reviewer_admin_id bigint,
    verification_status character varying(255) NOT NULL,
    CONSTRAINT business_profile_business_type_check CHECK (((business_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CORPORATION'::character varying])::text[]))),
    CONSTRAINT business_profile_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: business_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.business_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.business_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart (
    cart_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    member_id bigint NOT NULL
);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart ALTER COLUMN cart_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_item (
    cart_item_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    menu_id bigint NOT NULL,
    quantity integer NOT NULL,
    store_id bigint NOT NULL,
    cart_id bigint NOT NULL,
    pickup_date date NOT NULL,
    pickup_time time(6) without time zone NOT NULL
);


--
-- Name: cart_item_cart_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_item ALTER COLUMN cart_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_cart_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_item_option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.cart_item_option (
    cart_item_option_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    menu_option_id bigint NOT NULL,
    cart_item_id bigint NOT NULL
);


--
-- Name: cart_item_option_cart_item_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.cart_item_option ALTER COLUMN cart_item_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_item_option_cart_item_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: fcm_registration; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.fcm_registration (
    fcm_registration_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    active boolean NOT NULL,
    last_registered_at timestamp(6) without time zone NOT NULL,
    member_id bigint NOT NULL,
    platform character varying(20) NOT NULL,
    registration_token character varying(512) NOT NULL,
    CONSTRAINT fcm_registration_platform_check CHECK (((platform)::text = 'WEB'::text))
);


--
-- Name: fcm_registration_fcm_registration_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.fcm_registration ALTER COLUMN fcm_registration_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fcm_registration_fcm_registration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    age integer,
    email character varying(255),
    gender character varying(255),
    member_status character varying(255) NOT NULL,
    member_type character varying(255) NOT NULL,
    name character varying(255),
    nickname character varying(255),
    phone_number character varying(255) NOT NULL,
    birth_date date,
    is_admin boolean DEFAULT false NOT NULL,
    order_status_notification_agreed boolean DEFAULT true NOT NULL,
    withdrawn_at timestamp(6) without time zone,
    CONSTRAINT member_gender_check CHECK (((gender)::text = ANY ((ARRAY['MALE'::character varying, 'FEMALE'::character varying, 'NONE'::character varying])::text[]))),
    CONSTRAINT member_member_status_check CHECK (((member_status)::text = ANY ((ARRAY['SIGNUP_IN_PROGRESS'::character varying, 'ACTIVE'::character varying, 'BUSINESS_PENDING'::character varying, 'BUSINESS_REJECTED'::character varying, 'WITHDRAWN'::character varying])::text[]))),
    CONSTRAINT member_member_type_check CHECK (((member_type)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'BUSINESS'::character varying])::text[])))
);


--
-- Name: member_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: member_terms_agreement; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.member_terms_agreement (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    agreed boolean NOT NULL,
    agreed_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    terms_id bigint NOT NULL
);


--
-- Name: member_terms_agreement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.member_terms_agreement ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.member_terms_agreement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu (
    menu_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    base_price integer NOT NULL,
    description character varying(200),
    image_url character varying(255),
    name character varying(100) NOT NULL,
    store_id bigint NOT NULL
);


--
-- Name: menu_menu_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu ALTER COLUMN menu_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_menu_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_option (
    menu_option_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    additional_price integer NOT NULL,
    name character varying(50) NOT NULL,
    menu_option_group_id bigint NOT NULL
);


--
-- Name: menu_option_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.menu_option_group (
    menu_option_group_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    is_multiple boolean NOT NULL,
    is_required boolean NOT NULL,
    name character varying(50) NOT NULL,
    menu_id bigint NOT NULL
);


--
-- Name: menu_option_group_menu_option_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_option_group ALTER COLUMN menu_option_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_option_group_menu_option_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: menu_option_menu_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.menu_option ALTER COLUMN menu_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.menu_option_menu_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification (
    notification_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    body character varying(500) NOT NULL,
    menu_summary character varying(150),
    notification_type character varying(50) NOT NULL,
    pickup_date date,
    pickup_time time(6) without time zone,
    read_at timestamp(6) without time zone,
    receiver_member_id bigint NOT NULL,
    reference_id bigint,
    reference_type character varying(50),
    store_name character varying(100),
    title character varying(100) NOT NULL,
    CONSTRAINT notification_notification_type_check CHECK (((notification_type)::text = ANY ((ARRAY['ORDER_ACCEPTED'::character varying, 'ORDER_REJECTED'::character varying, 'PICKUP_REMINDER_DAY_BEFORE'::character varying, 'NEW_ORDER_REQUEST'::character varying, 'ORDER_ACCEPT_DEADLINE_12H'::character varying, 'ORDER_ACCEPT_DEADLINE_1H'::character varying])::text[]))),
    CONSTRAINT notification_reference_type_check CHECK (((reference_type)::text = 'ORDER'::text))
);


--
-- Name: notification_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification ALTER COLUMN notification_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item (
    order_item_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    discount_amount integer NOT NULL,
    final_price integer NOT NULL,
    menu_id bigint NOT NULL,
    menu_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price integer NOT NULL,
    order_pk bigint NOT NULL
);


--
-- Name: order_item_option; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.order_item_option (
    order_item_option_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    option_id bigint NOT NULL,
    option_name character varying(255) NOT NULL,
    option_price integer NOT NULL,
    order_item_id bigint NOT NULL
);


--
-- Name: order_item_option_order_item_option_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item_option ALTER COLUMN order_item_option_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_option_order_item_option_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_item_order_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.order_item ALTER COLUMN order_item_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_item_order_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: orders; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.orders (
    order_pk bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    customer_name character varying(255) NOT NULL,
    customer_phone character varying(255) NOT NULL,
    group_name character varying(255),
    member_id bigint NOT NULL,
    order_id character varying(64) NOT NULL,
    order_status character varying(255) NOT NULL,
    payment_amount integer NOT NULL,
    payment_method character varying(255) NOT NULL,
    pickup_date date NOT NULL,
    pickup_time time(6) without time zone NOT NULL,
    requests text,
    total_discount_amount integer NOT NULL,
    total_original_price integer NOT NULL,
    store_id bigint NOT NULL,
    accepted_at timestamp(6) without time zone,
    cancel_reason character varying(100),
    cancel_refund_amount integer,
    cancel_refund_rate integer,
    cancelled_at timestamp(6) without time zone,
    cancelled_by character varying(255),
    cancelled_by_member_id bigint,
    pickup_completed_at timestamp(6) without time zone,
    reject_reason character varying(100),
    rejected_at timestamp(6) without time zone,
    CONSTRAINT orders_cancelled_by_check CHECK (((cancelled_by)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'OWNER'::character varying, 'SYSTEM'::character varying])::text[]))),
    CONSTRAINT orders_order_status_check CHECK (((order_status)::text = ANY ((ARRAY['PENDING'::character varying, 'PAID'::character varying, 'ACCEPTED'::character varying, 'COMPLETED'::character varying, 'REJECTED'::character varying, 'CANCELLED'::character varying])::text[]))),
    CONSTRAINT orders_payment_method_check CHECK (((payment_method)::text = ANY ((ARRAY['PREPAID'::character varying, 'ON_SITE'::character varying])::text[])))
);


--
-- Name: orders_order_pk_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.orders ALTER COLUMN order_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_order_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments (
    payment_pk bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    approved_at timestamp(6) without time zone,
    canceled_at timestamp(6) without time zone,
    card_approve_no character varying(255),
    failure_code character varying(255),
    failure_message text,
    is_partial_cancelable boolean,
    last_transaction_key character varying(255),
    member_id bigint NOT NULL,
    method character varying(255),
    order_id character varying(64) NOT NULL,
    paid_amount integer NOT NULL,
    payment_key character varying(255),
    payment_provider character varying(255) NOT NULL,
    payment_status character varying(255) NOT NULL,
    payment_type character varying(255) NOT NULL,
    receipt_url character varying(255),
    refunded_amount integer,
    remaining_amount integer NOT NULL,
    total_order_amount integer NOT NULL,
    order_pk bigint NOT NULL,
    CONSTRAINT payments_payment_provider_check CHECK (((payment_provider)::text = 'TOSS'::text)),
    CONSTRAINT payments_payment_status_check CHECK (((payment_status)::text = ANY ((ARRAY['READY'::character varying, 'IN_PROGRESS'::character varying, 'DONE'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying, 'PARTIAL_CANCELED'::character varying])::text[]))),
    CONSTRAINT payments_payment_type_check CHECK (((payment_type)::text = ANY ((ARRAY['PREPAID'::character varying, 'ON_SITE'::character varying])::text[])))
);


--
-- Name: payments_payment_pk_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments ALTER COLUMN payment_pk ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_payment_pk_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: phone_verification; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.phone_verification (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    code character varying(255) NOT NULL,
    expired_at timestamp(6) without time zone NOT NULL,
    phone_number character varying(255) NOT NULL,
    used boolean NOT NULL,
    verified boolean NOT NULL,
    verified_at timestamp(6) without time zone
);


--
-- Name: phone_verification_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.phone_verification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.phone_verification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    content text,
    event_type character varying(255) NOT NULL,
    headcount integer NOT NULL,
    owner_reply_content text,
    per_person_budget integer NOT NULL,
    rating integer NOT NULL,
    replied_at timestamp(6) without time zone,
    member_id bigint NOT NULL,
    order_id bigint NOT NULL,
    store_id bigint NOT NULL,
    CONSTRAINT review_event_type_check CHECK (((event_type)::text = ANY ((ARRAY['LECTURE'::character varying, 'SEMINAR'::character varying, 'WORKSHOP'::character varying, 'SMALL_GROUP'::character varying, 'ETC'::character varying])::text[])))
);


--
-- Name: review_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: review_image; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.review_image (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    image_url character varying(1000) NOT NULL,
    review_id bigint NOT NULL
);


--
-- Name: review_image_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.review_image ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.review_image_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: settlements; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.settlements (
    settlement_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    charge_amount integer NOT NULL,
    order_amount integer NOT NULL,
    owner_id bigint NOT NULL,
    payout_amount integer NOT NULL,
    platform_fee_amount integer NOT NULL,
    settled_at timestamp(6) without time zone,
    settlement_status character varying(255) NOT NULL,
    settlement_type character varying(255) NOT NULL,
    order_pk bigint NOT NULL,
    store_id bigint NOT NULL,
    CONSTRAINT settlements_settlement_status_check CHECK (((settlement_status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'CANCELED'::character varying])::text[]))),
    CONSTRAINT settlements_settlement_type_check CHECK (((settlement_type)::text = ANY ((ARRAY['PAYOUT'::character varying, 'FEE_CHARGE'::character varying])::text[])))
);


--
-- Name: settlements_settlement_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.settlements ALTER COLUMN settlement_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.settlements_settlement_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: social_account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social_account (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    email character varying(255),
    member_id bigint NOT NULL,
    provider character varying(255) NOT NULL,
    provider_user_id character varying(255) NOT NULL,
    CONSTRAINT social_account_provider_check CHECK (((provider)::text = ANY ((ARRAY['KAKAO'::character varying, 'NAVER'::character varying, 'GOOGLE'::character varying])::text[])))
);


--
-- Name: social_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.social_account ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store (
    store_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    address character varying(255) NOT NULL,
    category character varying(50),
    closed_days character varying(255),
    description character varying(100),
    discount_condition_quantity integer,
    discount_rate integer,
    image_url character varying(255),
    max_price integer,
    min_order_days integer,
    min_price integer,
    order_process text,
    owner_id bigint NOT NULL,
    phone_number character varying(20) NOT NULL,
    pickup_close_time time(6) without time zone,
    pickup_open_time time(6) without time zone,
    review_count integer,
    review_rating double precision,
    store_name character varying(100) NOT NULL,
    region character varying(50),
    detail_address character varying(255),
    district character varying(50),
    neighborhood character varying(50),
    dong character varying(20),
    total_rating_score bigint,
    CONSTRAINT store_region_check CHECK (((region)::text = ANY ((ARRAY['GANGNAM'::character varying, 'GANGDONG'::character varying, 'GANGBUK'::character varying, 'GANGSEO'::character varying, 'GWANAK'::character varying, 'GWANGJIN'::character varying, 'GURO'::character varying, 'GEUMCHEON'::character varying, 'NOWON'::character varying, 'DOBONG'::character varying, 'DONGDAEMUN'::character varying, 'DONGJAK'::character varying, 'MAPO'::character varying, 'SEODAEMUN'::character varying, 'SEOCHO'::character varying, 'SEONGDONG'::character varying, 'SEONGBUK'::character varying, 'SONGPA'::character varying, 'YANGCHEON'::character varying, 'YEONGDEUNGPO'::character varying, 'YONGSAN'::character varying, 'EUNPYEONG'::character varying, 'JONGNO'::character varying, 'JUNG'::character varying, 'JUNGNANG'::character varying])::text[])))
);


--
-- Name: store_order_schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_order_schedule (
    store_order_schedule_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    end_date date NOT NULL,
    min_order_days integer NOT NULL,
    start_date date NOT NULL,
    store_id bigint NOT NULL
);


--
-- Name: store_order_schedule_day; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.store_order_schedule_day (
    store_order_schedule_day_id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    available boolean NOT NULL,
    day_of_week character varying(20) NOT NULL,
    interval_minutes integer NOT NULL,
    max_order_quantity integer,
    min_order_quantity integer,
    pickup_close_time time(6) without time zone,
    pickup_open_time time(6) without time zone,
    store_order_schedule_id bigint NOT NULL,
    break_end_time time(6) without time zone,
    break_start_time time(6) without time zone,
    pickup_end_time time(6) without time zone,
    pickup_start_time time(6) without time zone,
    CONSTRAINT store_order_schedule_day_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);


--
-- Name: store_order_schedule_day_store_order_schedule_day_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_order_schedule_day ALTER COLUMN store_order_schedule_day_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_order_schedule_day_store_order_schedule_day_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_order_schedule_store_order_schedule_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store_order_schedule ALTER COLUMN store_order_schedule_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_order_schedule_store_order_schedule_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: store_store_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.store ALTER COLUMN store_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_store_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: terms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.terms (
    id bigint NOT NULL,
    created_at timestamp without time zone,
    deleted_at timestamp without time zone,
    updated_at timestamp without time zone,
    active boolean NOT NULL,
    content text,
    required boolean NOT NULL,
    target_type character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    version character varying(255) NOT NULL,
    type character varying(255),
    CONSTRAINT terms_target_type_check CHECK (((target_type)::text = ANY ((ARRAY['COMMON'::character varying, 'CUSTOMER'::character varying, 'BUSINESS'::character varying])::text[])))
);


--
-- Name: terms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.terms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.terms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: business_profile business_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_profile
    ADD CONSTRAINT business_profile_pkey PRIMARY KEY (id);


--
-- Name: cart_item_option cart_item_option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item_option
    ADD CONSTRAINT cart_item_option_pkey PRIMARY KEY (cart_item_option_id);


--
-- Name: cart_item cart_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT cart_item_pkey PRIMARY KEY (cart_item_id);


--
-- Name: cart cart_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT cart_pkey PRIMARY KEY (cart_id);


--
-- Name: fcm_registration fcm_registration_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_registration
    ADD CONSTRAINT fcm_registration_pkey PRIMARY KEY (fcm_registration_id);


--
-- Name: member member_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT member_pkey PRIMARY KEY (id);


--
-- Name: member_terms_agreement member_terms_agreement_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member_terms_agreement
    ADD CONSTRAINT member_terms_agreement_pkey PRIMARY KEY (id);


--
-- Name: menu_option_group menu_option_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_option_group
    ADD CONSTRAINT menu_option_group_pkey PRIMARY KEY (menu_option_group_id);


--
-- Name: menu_option menu_option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_option
    ADD CONSTRAINT menu_option_pkey PRIMARY KEY (menu_option_id);


--
-- Name: menu menu_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT menu_pkey PRIMARY KEY (menu_id);


--
-- Name: notification notification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (notification_id);


--
-- Name: order_item_option order_item_option_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_option
    ADD CONSTRAINT order_item_option_pkey PRIMARY KEY (order_item_option_id);


--
-- Name: order_item order_item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT order_item_pkey PRIMARY KEY (order_item_id);


--
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (order_pk);


--
-- Name: payments payments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT payments_pkey PRIMARY KEY (payment_pk);


--
-- Name: phone_verification phone_verification_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.phone_verification
    ADD CONSTRAINT phone_verification_pkey PRIMARY KEY (id);


--
-- Name: review_image review_image_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT review_image_pkey PRIMARY KEY (id);


--
-- Name: review review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT review_pkey PRIMARY KEY (id);


--
-- Name: settlements settlements_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT settlements_pkey PRIMARY KEY (settlement_id);


--
-- Name: social_account social_account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_account
    ADD CONSTRAINT social_account_pkey PRIMARY KEY (id);


--
-- Name: store_order_schedule_day store_order_schedule_day_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule_day
    ADD CONSTRAINT store_order_schedule_day_pkey PRIMARY KEY (store_order_schedule_day_id);


--
-- Name: store_order_schedule store_order_schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule
    ADD CONSTRAINT store_order_schedule_pkey PRIMARY KEY (store_order_schedule_id);


--
-- Name: store store_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store
    ADD CONSTRAINT store_pkey PRIMARY KEY (store_id);


--
-- Name: terms terms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.terms
    ADD CONSTRAINT terms_pkey PRIMARY KEY (id);


--
-- Name: payments uk35yqdahtiysne6iij9ske72bj; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk35yqdahtiysne6iij9ske72bj UNIQUE (payment_key);


--
-- Name: cart uk7dds3r67nkhxm9sbs9r5obd46; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart
    ADD CONSTRAINT uk7dds3r67nkhxm9sbs9r5obd46 UNIQUE (member_id);


--
-- Name: settlements uk8h5i14i265fvl240pyeku4b05; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT uk8h5i14i265fvl240pyeku4b05 UNIQUE (order_pk);


--
-- Name: payments uk8vo36cen604as7etdfwmyjsxt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk8vo36cen604as7etdfwmyjsxt UNIQUE (order_id);


--
-- Name: payments uk98g0xqbscndq7wojfqrsx5nh; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT uk98g0xqbscndq7wojfqrsx5nh UNIQUE (order_pk);


--
-- Name: business_profile uk_business_profile_member_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_profile
    ADD CONSTRAINT uk_business_profile_member_id UNIQUE (member_id);


--
-- Name: business_profile uk_business_profile_registration_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.business_profile
    ADD CONSTRAINT uk_business_profile_registration_number UNIQUE (business_registration_number);


--
-- Name: social_account uk_social_account_provider_user_id; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social_account
    ADD CONSTRAINT uk_social_account_provider_user_id UNIQUE (provider, provider_user_id);


--
-- Name: store_order_schedule_day uk_store_order_schedule_day_schedule_day; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule_day
    ADD CONSTRAINT uk_store_order_schedule_day_schedule_day UNIQUE (store_order_schedule_id, day_of_week);


--
-- Name: store_order_schedule uk_store_order_schedule_store_period; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule
    ADD CONSTRAINT uk_store_order_schedule_store_period UNIQUE (store_id, start_date, end_date);


--
-- Name: member ukhh9kg6jti4n1eoiertn2k6qsc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT ukhh9kg6jti4n1eoiertn2k6qsc UNIQUE (nickname);


--
-- Name: orders ukhmsk25beh6atojvle1xuymjj0; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT ukhmsk25beh6atojvle1xuymjj0 UNIQUE (order_id);


--
-- Name: fcm_registration ukj9khs3kcdra1q7frtgn7olw4q; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.fcm_registration
    ADD CONSTRAINT ukj9khs3kcdra1q7frtgn7olw4q UNIQUE (registration_token);


--
-- Name: member ukmbmcqelty0fbrvxp1q58dn57t; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.member
    ADD CONSTRAINT ukmbmcqelty0fbrvxp1q58dn57t UNIQUE (email);


--
-- Name: review uktiskff7r4st2lhquiwdt9s0be; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT uktiskff7r4st2lhquiwdt9s0be UNIQUE (order_id);


--
-- Name: review_image fk16wp089tx9nm0obc217gvdd6l; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review_image
    ADD CONSTRAINT fk16wp089tx9nm0obc217gvdd6l FOREIGN KEY (review_id) REFERENCES public.review(id);


--
-- Name: cart_item fk1uobyhgl1wvgt1jpccia8xxs3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item
    ADD CONSTRAINT fk1uobyhgl1wvgt1jpccia8xxs3 FOREIGN KEY (cart_id) REFERENCES public.cart(cart_id);


--
-- Name: store_order_schedule fk4lgt33dgh29hkiamyncq7gt3b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule
    ADD CONSTRAINT fk4lgt33dgh29hkiamyncq7gt3b FOREIGN KEY (store_id) REFERENCES public.store(store_id);


--
-- Name: menu fk4sgenfcmk1jajhgctnkpn5erg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu
    ADD CONSTRAINT fk4sgenfcmk1jajhgctnkpn5erg FOREIGN KEY (store_id) REFERENCES public.store(store_id);


--
-- Name: orders fk5n14sr4mswfdtaoiwj7rkt0mw; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT fk5n14sr4mswfdtaoiwj7rkt0mw FOREIGN KEY (store_id) REFERENCES public.store(store_id);


--
-- Name: order_item fk5ocbuqb93h228ntv6fdrsye07; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item
    ADD CONSTRAINT fk5ocbuqb93h228ntv6fdrsye07 FOREIGN KEY (order_pk) REFERENCES public.orders(order_pk);


--
-- Name: review fk74d12ba8sxxu9vpnc59b43y30; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fk74d12ba8sxxu9vpnc59b43y30 FOREIGN KEY (store_id) REFERENCES public.store(store_id);


--
-- Name: order_item_option fk99n8bngv9kwtlx5rspidxkjee; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.order_item_option
    ADD CONSTRAINT fk99n8bngv9kwtlx5rspidxkjee FOREIGN KEY (order_item_id) REFERENCES public.order_item(order_item_id);


--
-- Name: store_order_schedule_day fkb41wfqn9v1j4xjvmfa8bnwa4f; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.store_order_schedule_day
    ADD CONSTRAINT fkb41wfqn9v1j4xjvmfa8bnwa4f FOREIGN KEY (store_order_schedule_id) REFERENCES public.store_order_schedule(store_order_schedule_id);


--
-- Name: menu_option_group fkdfq9q6voirejckjget2ig250; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_option_group
    ADD CONSTRAINT fkdfq9q6voirejckjget2ig250 FOREIGN KEY (menu_id) REFERENCES public.menu(menu_id);


--
-- Name: menu_option fkf3f59id3b6fmulimxsgpud9nq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.menu_option
    ADD CONSTRAINT fkf3f59id3b6fmulimxsgpud9nq FOREIGN KEY (menu_option_group_id) REFERENCES public.menu_option_group(menu_option_group_id);


--
-- Name: settlements fkhkllxr2su7lxukdkjj11420n; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT fkhkllxr2su7lxukdkjj11420n FOREIGN KEY (store_id) REFERENCES public.store(store_id);


--
-- Name: cart_item_option fkjypsiabdaj6ymcgx5hnll2aq; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.cart_item_option
    ADD CONSTRAINT fkjypsiabdaj6ymcgx5hnll2aq FOREIGN KEY (cart_item_id) REFERENCES public.cart_item(cart_item_id);


--
-- Name: review fkk0ccx5i4ci2wd70vegug074w1; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fkk0ccx5i4ci2wd70vegug074w1 FOREIGN KEY (member_id) REFERENCES public.member(id);


--
-- Name: review fknkc5s3da46cbx8oeqrfhnm7es; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.review
    ADD CONSTRAINT fknkc5s3da46cbx8oeqrfhnm7es FOREIGN KEY (order_id) REFERENCES public.orders(order_pk);


--
-- Name: settlements fkotr0hjsoxpbkb9ogycvnt9ph4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.settlements
    ADD CONSTRAINT fkotr0hjsoxpbkb9ogycvnt9ph4 FOREIGN KEY (order_pk) REFERENCES public.orders(order_pk);


--
-- Name: payments fkrg9ei6ejdorq8vvf3a6w41h7w; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments
    ADD CONSTRAINT fkrg9ei6ejdorq8vvf3a6w41h7w FOREIGN KEY (order_pk) REFERENCES public.orders(order_pk);


--
-- PostgreSQL database dump complete
--
